highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: FÃ¡bio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /LenkaKrenkova/
title: Lenka Krenkova's Resume
name: Lenka Krenkova
email: l.krenkova.lenka@gmail.com
email_full: mailto:l.krenkova.lenka@gmail.com
website: github.io/online-cv.github.io/
website_full: https://lenkakr.github.io/online-cv.github.io/
github: https://github.com/Lenkakr
twitter: twitter
tel: +358 2567183
tel_full: tel:+440000000000
google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address:
  street: Suolakivenkatu 16
  postcode: 00810
  city: Helsinki
  country: Finland
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
